### ISSUE TITLE
running PWA on ios/android web does not work

### ISSUE THREAD

**Issue by wallaceturner** [ionic-team/photo-gallery-capacitor-react#4] opened 2020-02-20 03:24 UTC
I've got the demo working on the desktop browser - that is when i click the camera button i get the popup confirming access to the webcam - i can then take photos and everything works as normal.

Trying the same on android (Chrome) and iOS (also Chrome) the button appears to do nothing. 

i tried removing the call to `defineCustomElements` to see what effect that has and i then do get an error message as expected so it seems it is doing something but not enough to get it working

**Comment by wallaceturner** [comment] 2020-02-21 01:11
it appears running over https fixes some of the issues however there are some cases left that do not work :
1) running as PWA from iphone on safari
2) running on browser from iphone on chrome (not PWA)

**Comment by dalmo3** [comment] 2020-08-11 05:51
I had a similar problem and fixed by adding this to `index.tsx`:
```
if (isPlatform("desktop")) defineCustomElements(window);
```

**Comment by Dorfaun** [comment] 2021-03-23 02:40
I followed the tutorial step by step and when I put it to run, it appeared
[react-scripts] ./node_modules/@ionic/core/dist/esm-es5/animation-096c6391.js
[react-scripts] Attempted import error: '__spreadArray' is not exported from 'tslib'.

**Comment by jcesarmobile** [comment] 2022-01-21 13:47
Camera plugin uses getUserMedia, which requires a secure context, so yeah, you have to use https to load. I use ngrok, it creates a https url for my localhost.

The issue is from 2020, I think back then getUserMedia was not supported on iOS, support was included in iOS 14.x, and also in WKWebView (that Chrome on iPhone uses) in a later release also on 14.x.

Also, I think camera plugin uses an input file with capture attribute when getUserMedia is not available now.

**Closed as completed by jcesarmobile** 2022-01-21 13:47 UTC
